build: false

environment:
  matrix:
    - PYTHON: "C:\\Python2-64"
      PYTHON_VERSION: "2"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python2-32"
      PYTHON_VERSION: "2"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python3-64"
      PYTHON_VERSION: "3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python3-32"
      PYTHON_VERSION: "3"
      PYTHON_ARCH: "32"

branches:
  only:
    - master

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install flake8"

test_script:
  - "%PYTHON%/Scripts/flake8.exe ./vss-ransom-restore/"
  - "./build.bat"

artifacts:
  - path: "vss-ransom-restore_*.exe"
