build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      ARTIFACT_MARKER: "py2_32bit"
    - PYTHON: "C:\\Python27-x64"
      ARTIFACT_MARKER: "py2_64bit"
    - PYTHON: "C:\\Python36"
      ARTIFACT_MARKER: "py3_32bit"
    - PYTHON: "C:\\Python36-x64"
      ARTIFACT_MARKER: "py3_64bit"

branches:
  only:
    - master

init:
  - "ECHO %PYTHON%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements.txt"
  - "pip install flake8"

test_script:
  - "flake8 ./vss-ransom-restore/"
  - "./build.bat nopause"

artifacts:
  - path: "dist/vss-ransom-restore_*.exe"
    name: "vss-ransom-restore_%ARTIFACT_MARKER%.exe"
